### ISSUE TITLE
Nginx is showing always after generating ngrok url

### ISSUE THREAD

**Issue by ezekel** [wernight/docker-ngrok#58]
Hi need some help please, after I added the image of wernight/ngrok, I rebuild my docker, when it goes up

I run this

 docker run --rm -it --network  myapp_default  --link webcontainer  wernight/ngrok ngrok http webcontainer:80

but when it generates the link of ngrok

when I click on it will display nginx index page it says successfully installed nginx.

when I run my app, I use myapp.local

please help

Thank you in advance

```

version: "3.8"
services:

  web:
    image: nginx:stable
    container_name: webcontainer
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/myapp
    expose:
      - 9000
    external_links:
      - php
      - db
  ngrok:
    image: wernight/ngrok
    links:
      - web
    ports:
      - "4040:4040"
    env_file: .env
    environment:
      NGROK_PORT: web:80

```
