### ISSUE TITLE
Cannot link to webcontainer

### ISSUE THREAD

**Issue by ezekel** [wernight/docker-ngrok#59]
Can someone help me please why I cannot link to my nginx container ?

```
 web:
    image: nginx:stable
    container_name: webcontainer
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/myapp
      - ./myapp.conf:/etc/nginx/conf.d/myapp.conf
    expose:
      - 9000
    external_links:
      - php
      - db
      - ngrok
  ngrok:
    image: wernight/ngrok
    ports:
      - "4040:4040"
     ```

```
CONTAINER ID   IMAGE            COMMAND                  CREATED         STATUS         PORTS                               NAMES
21f0c4080ab4   nginx:stable     "/docker-entrypoint.…"   2 minutes ago   Up 2 minutes   0.0.0.0:80->80/tcp, 9000/tcp        webcontainer
```

when I run this command

```
docker run --rm -it --link webcontainer wernight/ngrok ngrok http webcontainer:80
```

I will get an error

```
docker: Error response from daemon: Cannot link to /webcontainer, as it does not belong to the default network.
```

please help I'm confuse

Thank you in advance
