### ISSUE TITLE
Specifying hostname to forward request

### ISSUE THREAD

**Issue by bkuhl** [wernight/docker-ngrok#6]
I was experiencing an issue where ngrok could not access localhost:80.  It looked like ngrok was trying to take an external request into the docker container and fowarding it to `localhost:80` which it couldn't find.

![screen shot 2016-10-11 at 12 53 29 pm](https://cloud.githubusercontent.com/assets/524933/19281728/91363ed2-8fb9-11e6-8247-1f7e6360c570.png)

Here's an example of my _not functional_ config:

```
version: '2'

services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
  ngrok:
    image: wernight/ngrok
    links:
      - web
    ports:
      - "4040:4040"
    env_file: .env
```

** The solution** was to tell it to forward incoming requests to `web:80`.  I was able to achieve this with the following configuration:

```
  ngrok:
    image: wernight/ngrok
    links:
      - web
    ports:
      - "4040:4040"
    env_file: .env
    environment:
      NGROK_PORT: web:80
```

In this case I happened to resolve the issue but wanted to post it here in case it was helpful to someone else.
